services:
  redis:
    image: redis:alpine
    container_name: redis_container
    networks:
      - transcendence_net

  backend:
    build: ./backend
    container_name: game_server
    ports:
      - "3000"
    depends_on:
      - redis
    networks:
      - transcendence_net
    volumes:
      - ./backend:/usr/src/app/
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  matchmaking-service:
    build: ./logic-service # Assicurati che il percorso sia corretto rispetto a dove metti questo file
    container_name: matchmaking_container
    ports:
      - "3500"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=development
    networks:
      - transcendence_net

  frontend:
     build: ./frontend
     container_name: game_client
     ports:
      - "5173"
     volumes:
      - ./frontend:/usr/src/app/
      - /usr/src/app/node_modules
     environment:
      - VITE_API_URL=http://localhost:3000
     networks:
      - transcendence_net

  nginx:
    build: ./nginx
    container_name: reverse_proxy
    ports:
      - "80:80"
    networks:
      - transcendence_net
    depends_on:
      - backend
      - matchmaking-service
      - frontend
networks:
  transcendence_net:
    driver: bridge
