services:
    postgres:
        container_name: transcendence_postgres
        image: postgres:17-alpine
        restart: unless-stopped
        networks:
            - backend-network
        expose:
            - "5432"
        env_file:
            - .env.shared
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}",
                ]
            interval: 5s
            timeout: 5s
            retries: 5
    db-migration:
        container_name: transcendence_db_migration
        image: transcendence_db_migration:20-alpine
        build:
            context: .
            dockerfile: ./db-migration/Dockerfile
        depends_on:
            postgres:
                condition: service_healthy
        restart: "no"
        networks:
            - backend-network
        env_file:
            - .env.shared
        volumes:
            - ./shared/prisma:/app/prisma

    auth-service:
        build:
            context: .
            dockerfile: ./auth-service/Dockerfile
        container_name: transcendence_auth_service
        env_file:
            - ./auth-service/.env
            - .env.shared
        depends_on:
            postgres:
                condition: service_healthy
        networks:
            - backend-network
        expose:
            - "3002"

    user-service:
        container_name: transcendence_user_service
        image: transcendence_user_service:20-alpine
        build:
            context: .
            dockerfile: ./user-service/Dockerfile
            target: build
        depends_on:
            db-migration:
                condition: service_completed_successfully
        command: sh -c "npm run prisma:generate && npm run start:dev"
        restart: unless-stopped
        networks:
            - backend-network
        expose:
            - "3001"
        ports:
            - "127.0.0.1:3001:3001"
        env_file:
            - .env.shared
        volumes:
            - ./user-service/src:/app/user-service/src
            - ./shared/prisma/schema.prisma:/app/prisma/schema.prisma:ro
            - uploads_data:/uploads
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "wget -qO- http://localhost:3001/health || exit 1",
                ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 15s

    game-service:
        container_name: transcendence_game_service
        image: transcendence_game_service:20-alpine
        build:
            context: .
            dockerfile: ./game-service/Dockerfile
            target: build
        depends_on:
            db-migration:
                condition: service_completed_successfully
        command: sh -c "npm run prisma:generate && npm run start:dev"
        restart: unless-stopped
        networks:
            - backend-network
        expose:
            - "3000"
        env_file:
            - .env.shared
        volumes:
            - ./game-service/src:/app/game-service/src
            - ./shared/prisma/schema.prisma:/app/prisma/schema.prisma:ro
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "wget -qO- http://localhost:3000/health || exit 1",
                ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 15s

    gateway:
        image: nginx:stable-alpine
        container_name: api_gateway
        ports:
            - "2443:2443"
        volumes:
            - ./frontend:/usr/share/nginx/html:ro
            - ./nginix/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./certs:/etc/nginx/certs
        depends_on:
            - auth-service
            - user-service
            - game-service
        networks:
            - backend-network

    ngrok:
        image: ngrok/ngrok:3
        container_name: ngrok
        command: http https://gateway:2443
        env_file:
            - .env.shared
        environment:
            - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
        depends_on:
            - gateway
        ports:
            - "4040:4040"
        networks:
            - backend-network

volumes:
    postgres_data:
    uploads_data:

networks:
    backend-network:
        driver: bridge
