
events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;

    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    server {
        listen 2080;
        server_name _;
        return 301 https://$host:2443$request_uri;
    }

    server {
        listen 2443 ssl;
        server_name _;

        ssl_certificate     /etc/nginx/certs/cert.crt;
        ssl_certificate_key /etc/nginx/certs/cert.key;


        ssl_protocols TLSv1.2 TLSv1.3;

        # FRONTEND
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }


        location /api/ {
            proxy_pass http://auth_service:3000/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }


        # PROFILE SERVICE
        location /profile/ {
            proxy_pass http://profile_service:3001/profile/;
            proxy_http_version 1.1;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";

            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_read_timeout 86400;
        }

        # GAME SERVICE (HTTP REST)
        # location /game/ {
        #     proxy_pass http://game_service:3002; # No trailing slash
        # }

        location /game/ {
            proxy_pass http://game_service:3002/game/;
            proxy_http_version 1.1;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_cache_bypass $http_upgrade;

            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_read_timeout 86400;
        }
        # Correct Nginx for Socket.io
        # location /socket.io/ {
        #     proxy_pass http://game_service:3002; # No trailing slash
        #     proxy_http_version 1.1;
        #     proxy_set_header Upgrade $http_upgrade;
        #     proxy_set_header Connection "Upgrade";
        #     proxy_cache_bypass $http_upgrade;
        # }

        location /socket.io/ {
            proxy_pass http://game_service:3002/socket.io/;
            proxy_http_version 1.1;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";

            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_read_timeout 86400;
        }

    }
}