# --- Stage 1: Build ---
FROM node:20-alpine AS build

WORKDIR /app

# Install OpenSSL for Prisma
RUN apk add --no-cache openssl

# Copy dependency files and Prisma schema
COPY game-service/package*.json ./
COPY shared_storage/prisma/schema.prisma ./prisma/schema.prisma

# Install dependencies
RUN npm install

# Copy source code
COPY game-service/. .

# Generate Prisma Client and build the application
RUN npx prisma generate
RUN npm run build

# --- Stage 2: Production ---
FROM node:20-alpine

WORKDIR /app

# Copy built artifacts and modules from the builder stage
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package*.json ./
COPY --from=build /app/dist ./dist
COPY --from=build /app/prisma ./prisma

EXPOSE 3000

CMD ["node", "dist/main"]