import { ApiProperty, ApiPropertyOptional } from "@nestjs/swagger";
import {
	IsEnum,
	IsOptional,
	IsString,
	IsUrl,
	MinLength,
} from "class-validator";
import { UserStatus } from "../enums";
import {
	IsEmailField,
	IsUsernameField,
	IsPasswordHashField,
	IsOAuthIdField,
} from "./field-validators";

/**
 * Input DTO for setting a password.
 * Password must be pre-hashed by the auth-service.
 */
export class SetPasswordDto {
	@IsPasswordHashField()
	passwordHash: string;
}

/**
 * Input DTO for updating a password.
 * Password must be pre-hashed by the auth-service.
 */
export class UpdatePasswordDto {
	@IsPasswordHashField()
	passwordHash: string;
}

/**
 * Update username.
 * If the user still has a default DiceBear avatar, it will be regenerated.
 */
export class UpdateUsernameDto {
	@IsUsernameField()
	username: string;
}

/**
 * Input DTO for updating email.
 */
export class UpdateEmailDto {
	@IsEmailField()
	email: string;
}

/**
 * Input DTO for updating user status.
 */
export class UpdateStatusDto {
	@ApiProperty({
		description: "New user status",
		enum: UserStatus,
		example: "ONLINE",
	})
	@IsEnum(UserStatus, {
		message: `Status must be one of: ${Object.values(UserStatus).join(", ")}`,
	})
	status: UserStatus;
}

/**
 * Input DTO for linking an OAuth account to an existing user.
 */
export class LinkOAuthDto {
	@IsOAuthIdField()
	oauthId: string;

	@ApiPropertyOptional({
		description:
			"Avatar URL from OAuth provider. Overwrites avatar only if the current one is a default DiceBear.",
		example: "https://lh3.googleusercontent.com/a/photo.jpg",
	})
	@IsOptional()
	@IsString()
	avatarUrl?: string;
}

/**
 * Input DTO for setting up 2FA.
 */
export class Setup2faDto {
	@ApiProperty({
		description: "TOTP secret generated by auth-service (base32 encoded)",
		example: "JBSWY3DPEHPK3PXP",
	})
	@IsString()
	@MinLength(1, { message: "2FA secret is required" })
	twoFactorSecret: string;
}