import { ApiProperty, ApiPropertyOptional } from "@nestjs/swagger";
import { IsOptional, IsString, MinLength } from "class-validator";
import { IsPasswordHashField, IsOAuthIdField, IsEmailField } from "./field-validators";

/**
 * Input DTO for setting a password (creates a new local account entry).
 * Password must be pre-hashed by the auth-service.
 * Used by auth-service to call user-service internal API.
 */
export class SetPasswordDto {
	@IsPasswordHashField()
	passwordHash: string;
}

/**
 * Input DTO for updating email.
 * Used by auth-service to call user-service internal API.
 */
export class UpdateEmailDto {
	@IsEmailField()
	email: string;
}

/**
 * Input DTO for updating a password.
 * Password must be pre-hashed by the auth-service.
 * Used by auth-service to call user-service internal API.
 */
export class UpdatePasswordDto {
	@IsPasswordHashField()
	passwordHash: string;
}

/**
 * Input DTO for linking an OAuth account to an existing user.
 * Used by auth-service to call user-service internal API.
 */
export class LinkOAuthDto {
	@IsOAuthIdField()
	oauthId: string;

	@ApiPropertyOptional({
		description:
			"Avatar URL from OAuth provider. Overwrites avatar only if the current one is a default DiceBear.",
		example: "https://lh3.googleusercontent.com/a/photo.jpg",
	})
	@IsOptional()
	@IsString()
	avatarUrl?: string;
}

/**
 * Input DTO for setting up 2FA.
 * Used by auth-service to call user-service internal API.
 */
export class Setup2faDto {
	@ApiProperty({
		description: "TOTP secret generated by auth-service (base32 encoded)",
		example: "JBSWY3DPEHPK3PXP",
	})
	@IsString()
	@MinLength(1, { message: "2FA secret is required" })
	twoFactorSecret: string;
}
