export const GameConfig = {
	SERVER: {
		TICK_RATE: 16,
		MAX_GAME_DURATION: 300.0,
		MAX_GAME_KILLS: 5,
		SHUTDOWN_TIMER: 4.0,
		MAX_INPUT_FOR_TICK: 10.0,
		MAX_DISCONNECTION_TIMER: 5.0,
		MAX_INPUT_QUEUE_SIZE: 100,
	},

	MAP: {
		CELL_SIZE: 5.0,
		WIDTH: 130,
		DEPTH: 130,
	},
	PLAYER: {
		DEFAULT_HP: 100,
		SPEED: 50.0,
		RADIUS: 0.8,
		RESPAWN_TIMER: 5.0,
		BOT_DB_ID: -1,
	},
	MATCH: {
		DEFAULT_PLAYERS_FOR_TEAM: 2, // Per gestire 2vs2, 2vs2vs2, ecc.
	},
	COMBAT: {
		MELEE_HITBOX_RADIUS: 2.0,
		SPELL_HITBOX_RADIUS: 0.5,
		ATTACK_RANGE_OFFSET: 1.5,
		SPELL_ATTACK_RANGE_OFFSET: 1.0,
		ATTACK_VISUALIZATION: 0.5,
		DEFENCE_DURATION: 1.5,
		BULLET_LIFE: 5.0,
	},
	RENDERING: {
    	CAMERA: {
      		ZOOM: 1,
      		HEIGHT: 150,
      		ANGLE: Math.PI / 4, // 45°
    	},
    	INTERPOLATION_SPEED: 0.15,
  	},
}