export enum AttackType {
	MELEE_ATTACK = "melee-attack",
	SPELL_ATTACK = "spell-attack",
	DEFENCE_ATTACK = "defence-attack",
}

export enum BulletHit {
	PLAYER_HIT = "player-hit",
	WALL_HIT = "wall-hit",
	NONE = "none",
}

export enum ErrorCode {
	/* ------- Game Errors ------- */
	PLAYER_NOT_FOUND = "PLAYER_NOT_FOUND",
	MATCH_ALREADY_STARTED = "MATCH_ALREADY_STARTED",
	MAP_LOAD_FAILED = "MAP_LOAD_FAILED",
	INVALID_INPUT = "INVALID_INPUT",
	UNAUTHORIZED = "UNAUTHORIZED",
	INTERNAL_ERROR = "INTERNAL_ERROR",
	SESSION_NOT_FOUND = "SESSION_NOT_FOUND",
	SERVER_SHUTDOWN = "SERVER_SHUTDOWN",

	/* ------- Connection / Auth Errors ------- */
    UNAUTHORIZED_TOKEN = "UNAUTHORIZED_TOKEN",

	/* ------- Matchmaking Errors ------- */
	ERROR_FETCHING_RANK = "ERROR_FETCHING_RANK",
    ERROR_ALREADY_IN_ANOTHER_GAME = "ERROR_ALREADY_IN_ANOTHER_GAME",
    MATCH_EXPIRED_BACK_TO_LOBBY = "MATCH_EXPIRED_BACK_TO_LOBBY",
    ERROR_SESSION_NOT_FOUND = "ERROR_SESSION_NOT_FOUND",
    ERROR_UNAUTHORIZED = "ERROR_UNAUTHORIZED",
}

export enum MatchmakingStatus {
    SEARCHING_QUEUED = "SEARCHING_QUEUED",
    SEARCHING_UNRANKED_MATCH = "SEARCHING_UNRANKED_MATCH",
    RECONNECTED_TO_GAME = "RECONNECTED_TO_GAME",
    RECONNECTED_TO_LOCAL_MATCH = "RECONNECTED_TO_LOCAL_MATCH",
    RECONNECTED_TO_AI_MATCH = "RECONNECTED_TO_AI_MATCH",
    MATCH_STARTING = "MATCH_STARTING",
    WAITING_FOR_OPPONENT = "WAITING_FOR_OPPONENT",
    LOCAL_MATCH_STARTED = "LOCAL_MATCH_STARTED",
    AI_MATCH_STARTED = "AI_MATCH_STARTED",
    LEFT_QUEUE_SUCCESS = "LEFT_QUEUE_SUCCESS",
    NOT_IN_QUEUE = "NOT_IN_QUEUE",
    MATCH_FINALIZED = "MATCH_FINALIZED",
    MATCH_ALREADY_CLEANED = "MATCH_ALREADY_CLEANED"
}

export enum SuccessCode {
	OK = "OK",
}
