export enum AttackType {
	MELEE_ATTACK = "MELEE_ATTACK",
	SPELL_ATTACK = "SPELL_ATTACK",
	DEFENCE_ATTACK = "DEFENCE_ATTACK",
}

export enum BulletHit {
	PLAYER_HIT = "PLAYER_HIT",
	WALL_HIT = "WALL_HIT",
	NONE = "NONE",
}

export enum ErrorCode {
	PLAYER_NOT_FOUND = "PLAYER_NOT_FOUND",
	MATCH_ALREADY_STARTED = "MATCH_ALREADY_STARTED",
	MAP_LOAD_FAILED = "MAP_LOAD_FAILED",
	INVALID_INPUT = "INVALID_INPUT",
	UNAUTHORIZED = "UNAUTHORIZED",
	INTERNAL_ERROR = "INTERNAL_ERROR",
	SESSION_NOT_FOUND = "SESSION_NOT_FOUND",
	SERVER_SHUTDOWN = "SERVER_SHUTDOWN",
}

export enum SuccessCode {
	OK = "OK",
}
