export const GameConfig = {
  SERVER: {
    TICK_RATE: 16,
    MAX_GAME_DURATION: 30.0,
    MAX_LOBBY_DURATION: 500.0,
    MAX_GAME_KILLS: 3,
    SHUTDOWN_TIMER: 4.0,
    HARD_LIMIT: 1500.0,
    MAX_INPUT_FOR_TICK: 10.0,
    MAX_DISCONNECTION_TIMER: 50.0,
    MAX_INPUT_QUEUE_SIZE: 100,
  },
  MAP: {
    CELL_SIZE: 5.0,
    WIDTH: 130,
    DEPTH: 130,
  },
  PLAYER: {
    DEFAULT_HP: 100,
    SPEED: 20.0,
    RADIUS: 2.7,
    RESPAWN_TIMER: 5.0,
  },
  MATCH: {
    DEFAULT_PLAYERS_FOR_TEAM: 2, // Per gestire 2vs2, 2vs2vs2, ecc.
  },
  COMBAT: {
    MELEE_HITBOX_RADIUS: 7.34,
    SPELL_HITBOX_RADIUS: 1.5,
    ATTACK_RANGE_OFFSET: 1.5,
    SPELL_ATTACK_RANGE_OFFSET: 1.0,
    ATTACK_VISUALIZATION: 0.5,
    DEFENCE_DURATION: 1.5,
    BULLET_LIFE: 5.0,
  },
  BOT: {
    MELEE_DANGER_ZONE: 25,
    BULLET_DANGER_ZONE: 400,
    VISUAL_RADIUS_SQ: 3000.0,
    WAYPOINT_TOLERANCE_SQ: 9.0,
    WANDER_STUCK_TIMER: 4.0,
    MAX_PATH_TIME: 2.5,
    SECURITY_RANGE: 10.0,
    SPELL_AIM_SPREAD_DEG: 20,
  },
  ACHIEVEMENT: {
    CLUTCHMASTER: 0.05,
  },
  RENDERING: {
    CAMERA: {
      ZOOM: 1,
      HEIGHT: 150,
      ANGLE: Math.PI / 4, // 45°
    },
    INTERPOLATION_SPEED: 0.15,
  },
};
